default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: caiodassumpcao
  password: caitole123
  host: localhost

development:
  <<: *default
  database: your_database_name

test:
  <<: *default
  database: your_database_name_test

production:
  <<: *default
  database: your_database_name_production